### ISSUE TITLE
[New feature] Math formulas in MarkDown

### ISSUE THREAD

**Issue by aniolm9** [craflin/umdoc#1]
Hi,
I think that it would be nice to translate the code inside `$` to LaTeX math expressions.
For example, typing `$\pi$` in MarkDown would give a `π` in the TEX and PDF files.

Thanks!

**Comment by craflin** [comment]
Hi,
thanks for taking interest in my little project. I like to finish my current ongoing work on an HTML generator first, then I'll implement your requested feature. It should not be that difficult.

**Comment by aniolm9** [comment]
Thanks! I find it very useful and I'll probably use it in a daily basis.

**Comment by craflin** [comment]
It's supported in 0.2.0
