### ISSUE TITLE
compilation error on OSX

### ISSUE THREAD

**Issue by kirk86** [craflin/umdoc#3]
I'm trying to compile the source (on OSX) and use it to translate mardown to latex but I keep getting the following errors.
```
CMake Error at CDeploy:157 (list):
  list GET given empty list
Call Stack (most recent call first):
  CDeploy:187 (get_target_os)
  CMakeLists.txt:9 (include)


CMake Error at CDeploy:166 (list):
  list GET given empty list
Call Stack (most recent call first):
  CDeploy:187 (get_target_os)
  CMakeLists.txt:9 (include)
```

Any ideas what's wrong here?

**Comment by craflin** [comment]
I've never tried to compile it on MacOS. (I don't own a Mac.) The failing CMake scripts tries to detect the OS name. It detects that it is not running on Windows so it runs some code that was designed for Linux and does not work on a Mac. I think I fixed this on the master branch. However, there are probably a lot more build issues. Umdoc uses my general purpose library libnstd, which is an abstraction of operating system features. It has never been compiled on a Mac, so it will probably not work.

**Comment by craflin** [comment]
see #13
